In [ ]:
%matplotlib inline


# Plot Ridge coefficients as a function of the regularization


Shows the effect of collinearity in the coefficients of an estimator.

.. currentmodule:: sklearn.linear_model

:class:`Ridge` Regression is the estimator used in this example.
Each color represents a different feature of the
coefficient vector, and this is displayed as a function of the
regularization parameter.

This example also shows the usefulness of applying Ridge regression
to highly ill-conditioned matrices. For such matrices, a slight
change in the target variable can cause huge variances in the
calculated weights. In such cases, it is useful to set a certain
regularization (alpha) to reduce this variation (noise).

When alpha is very large, the regularization effect dominates the
squared loss function and the coefficients tend to zero.
At the end of the path, as alpha tends toward zero
and the solution tends towards the ordinary least squares, coefficients
exhibit big oscillations. In practise it is necessary to tune alpha
in such a way that a balance is maintained between both.


In [1]:
# Author: Fabian Pedregosa -- <fabian.pedregosa@inria.fr>
# License: BSD 3 clause

print(__doc__)

import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

# X is the 10x10 Hilbert matrix
X = 1. / (np.arange(1, 11) + np.arange(0, 10)[:, np.newaxis])
y = np.ones(10)

Automatically created module for IPython interactive environment


Compute paths


In [2]:
n_alphas = 200
alphas = np.logspace(-10, -2, n_alphas)
clf = linear_model.Ridge(fit_intercept=False)

coefs = []
for a in alphas:
    clf.set_params(alpha=a)
    clf.fit(X, y)
    coefs.append(clf.coef_)

Display results


In [12]:
ax = plt.gca()

max_coefs = []
for item in coefs:
    max_coefs.append(max(item))
print(max_coefs)
ax.plot(alphas, coefs)
ax.set_xscale('log')
ax.set_xlim(ax.get_xlim()[::-1])  # reverse axis
plt.xlabel('alpha')
plt.ylabel('weights')
plt.title('Ridge coefficients as a function of the regularization')
plt.axis('tight')
plt.show()

[274.02303645049255, 265.22300143972569, 256.93547813333259, 249.14682288563986, 241.84083326391729, 234.99922885703634, 228.60209447588858, 222.62831453284466, 217.05593650701456, 211.86248367097201, 207.02524940219521, 202.52152835233824, 198.32883819814725, 194.42504546441651, 190.78852082315859, 187.39823154620194, 184.23380271853833, 181.27557106945923, 178.50460555620361, 175.9027358438282, 173.45252700921932, 171.13728258013367, 168.94101561611257, 166.84843177607019, 164.84488657607125, 162.9163692686904, 161.0494623017463, 159.23131680291806, 157.44962823945531, 155.69261651809109, 153.94901383037939, 152.20805339105195, 150.45948074286491, 148.69355485363522, 146.90107710144036, 145.0734178791252, 143.20255978188291, 141.28114621764834, 139.30254459242988, 137.260911556796, 135.1512681933128, 132.96957838089193, 130.71282615688776, 128.37909469996097, 125.96763389708214, 123.47892225724902, 120.91471099353041, 118.27804965382136, 115.57328949697023, 112.80605830312537, 109.98

In [ ]:
import heapq
ax = plt.gca()

max_coefs = []
for item in coefs:
    max_coefs.append(max(item))
ax.plot(alphas, max_coefs)
ax.set_xscale('log')
ax.set_xlim(ax.get_xlim()[::-1])  # reverse axis
plt.xlabel('alpha')
plt.ylabel('weights')
plt.title('Ridge coefficients as a function of the regularization')
plt.axis('tight')
plt.show()

In [7]:
len(alphas)

200

In [8]:
len(coefs)

200

In [4]:
X

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ,  0.2       ,
         0.16666667,  0.14285714,  0.125     ,  0.11111111,  0.1       ],
       [ 0.5       ,  0.33333333,  0.25      ,  0.2       ,  0.16666667,
         0.14285714,  0.125     ,  0.11111111,  0.1       ,  0.09090909],
       [ 0.33333333,  0.25      ,  0.2       ,  0.16666667,  0.14285714,
         0.125     ,  0.11111111,  0.1       ,  0.09090909,  0.08333333],
       [ 0.25      ,  0.2       ,  0.16666667,  0.14285714,  0.125     ,
         0.11111111,  0.1       ,  0.09090909,  0.08333333,  0.07692308],
       [ 0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
         0.1       ,  0.09090909,  0.08333333,  0.07692308,  0.07142857],
       [ 0.16666667,  0.14285714,  0.125     ,  0.11111111,  0.1       ,
         0.09090909,  0.08333333,  0.07692308,  0.07142857,  0.06666667],
       [ 0.14285714,  0.125     ,  0.11111111,  0.1       ,  0.09090909,
         0.08333333,  0.07692308,  0.07142857

In [6]:
y

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [7]:
alphas

array([  1.00000000e-10,   1.09698580e-10,   1.20337784e-10,
         1.32008840e-10,   1.44811823e-10,   1.58856513e-10,
         1.74263339e-10,   1.91164408e-10,   2.09704640e-10,
         2.30043012e-10,   2.52353917e-10,   2.76828663e-10,
         3.03677112e-10,   3.33129479e-10,   3.65438307e-10,
         4.00880633e-10,   4.39760361e-10,   4.82410870e-10,
         5.29197874e-10,   5.80522552e-10,   6.36824994e-10,
         6.98587975e-10,   7.66341087e-10,   8.40665289e-10,
         9.22197882e-10,   1.01163798e-09,   1.10975250e-09,
         1.21738273e-09,   1.33545156e-09,   1.46497140e-09,
         1.60705282e-09,   1.76291412e-09,   1.93389175e-09,
         2.12145178e-09,   2.32720248e-09,   2.55290807e-09,
         2.80050389e-09,   3.07211300e-09,   3.37006433e-09,
         3.69691271e-09,   4.05546074e-09,   4.44878283e-09,
         4.88025158e-09,   5.35356668e-09,   5.87278661e-09,
         6.44236351e-09,   7.06718127e-09,   7.75259749e-09,
         8.50448934e-09,

In [11]:
ridgeCV = linear_model.RidgeCV(alphas=alphas, fit_intercept=False)
ridgeCV.fit(X, y)

RidgeCV(alphas=array([  1.00000e-10,   1.09699e-10, ...,   9.11589e-03,   1.00000e-02]),
    cv=None, fit_intercept=False, gcv_mode=None, normalize=False,
    scoring=None, store_cv_values=False)

In [12]:
ridgeCV.alpha_

7.6634108680074628e-10

In [4]:
coefs

[array([   2.64506204,  -27.60371067,    7.99289328,  133.67547429,
          18.04323914, -123.85506337, -175.62005261, -113.78633101,
          45.1537891 ,  274.02303645]),
 array([   2.77495267,  -30.12097781,   17.90676304,  125.42566475,
          10.71784698, -122.8663481 , -168.64642068, -106.59630669,
          46.70072717,  265.22300144]),
 array([   2.89641305,  -32.48098287,   27.21873891,  117.65914583,
           3.83376536, -121.92540864, -162.07888197,  -99.831642  ,
          48.15082869,  256.93547813]),
 array([   3.00959599,  -34.6869713 ,   35.94234431,  110.36416989,
          -2.61958942, -121.03071236, -155.90692433,  -93.48138493,
          49.50637921,  249.14682289]),
 array([   3.1146896 ,  -36.74289558,   44.09396039,  103.52651027,
          -8.654894  , -120.18030871, -150.11799394,  -87.5326008 ,
          50.77012057,  241.84083326]),
 array([   3.2119094 ,  -38.65326603,   51.69224826,   97.12992707,
         -14.28643554, -119.3720103 , -144.69785707,