In [1]:
import numpy as np
import matplotlib as mpl
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
import time
from scipy.optimize import leastsq
from scipy import stats
import scipy.optimize as opt
import matplotlib.pyplot as plt
from scipy.stats import norm, poisson
from scipy.interpolate import BarycentricInterpolator
#from scipy.interpolate import CubicSpline
import scipy as sp
import math

In [5]:
t = 1000
a = np.zeros(10000)
for i in range(t):
    a += np.random.uniform(-5, 5, 10000)
a /= t
plt.hist(a, bins=100, normed=True)
plt.show()

In [21]:
lamda = 7
a = np.zeros(10000)
for i in range(t):
    a += np.random.poisson(lam=lamda, size=10000)
a
plt.hist(p, bins=100, normed=True)
plt.grid(True)
plt.show()

In [31]:
a = np.zeros(10000)
for i in range(t):
    a += np.random.exponential(size=10000, scale=13.0)
a /= t
print(a)
plt.hist(a, bins=100, normed=False)
plt.grid(True)
plt.show()

[ 13.26907725  12.66854677  13.14449312 ...,  14.16130262  13.269477
  12.72452188]


In [32]:
    x, y = np.mgrid[-3:3:7j, -3:3:7j]
    print(x)
    print(y)
    u = np.linspace(-3, 3, 101)
    x, y = np.meshgrid(u, u)
    print(x)
    print(y)
    z = x*y*np.exp(-(x**2 + y**2)/2) / math.sqrt(2*math.pi)
    # z = x*y*np.exp(-(x**2 + y**2)/2) / math.sqrt(2*math.pi)
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
    # ax.plot_surface(x, y, z, rstride=5, cstride=5, cmap=cm.coolwarm, linewidth=0.1)  #
    ax.plot_surface(x, y, z, rstride=3, cstride=3, cmap=cm.gist_heat, linewidth=0.5)
    plt.show()

[[-3. -3. -3. -3. -3. -3. -3.]
 [-2. -2. -2. -2. -2. -2. -2.]
 [-1. -1. -1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.  2.  2.]
 [ 3.  3.  3.  3.  3.  3.  3.]]
[[-3. -2. -1.  0.  1.  2.  3.]
 [-3. -2. -1.  0.  1.  2.  3.]
 [-3. -2. -1.  0.  1.  2.  3.]
 [-3. -2. -1.  0.  1.  2.  3.]
 [-3. -2. -1.  0.  1.  2.  3.]
 [-3. -2. -1.  0.  1.  2.  3.]
 [-3. -2. -1.  0.  1.  2.  3.]]
[[-3.   -2.94 -2.88 ...,  2.88  2.94  3.  ]
 [-3.   -2.94 -2.88 ...,  2.88  2.94  3.  ]
 [-3.   -2.94 -2.88 ...,  2.88  2.94  3.  ]
 ..., 
 [-3.   -2.94 -2.88 ...,  2.88  2.94  3.  ]
 [-3.   -2.94 -2.88 ...,  2.88  2.94  3.  ]
 [-3.   -2.94 -2.88 ...,  2.88  2.94  3.  ]]
[[-3.   -3.   -3.   ..., -3.   -3.   -3.  ]
 [-2.94 -2.94 -2.94 ..., -2.94 -2.94 -2.94]
 [-2.88 -2.88 -2.88 ..., -2.88 -2.88 -2.88]
 ..., 
 [ 2.88  2.88  2.88 ...,  2.88  2.88  2.88]
 [ 2.94  2.94  2.94 ...,  2.94  2.94  2.94]
 [ 3.    3.    3.   ...,  3.    3.    3.  ]]
